### ISSUE TITLE
Slow FPS

### ISSUE THREAD

**Issue by iboldurev** [MrMauro/buildroot_external_kivy#3]
Hi, I have a problem with an application running on raspberry 3b+ after launch i have 1 fps on the display.

**Comment by maovidal** [comment]
Hi Ivan:

It seems to me that solving the issues about the FPS in Kivy could quite tricky. But performing tests for single parts of your project can help to isolate the problem and identify the culprit.

I normally will test the application in a development computer where I address the issues related to the structure of the app. In my case I implement async (using [trio like this](https://github.com/kivy/kivy/blob/master/examples/async/trio_advanced.py)) as this allows my application dedicate processes that don't block Kivy's refresh and also monitor those with variables that tell me how long does every routine takes to complete.

Also, on for the deployment computer, I test a simple Kivy app from Kivy's examples. So far, in my case, I have noticed that the issues are related to the graphic drivers. Unfortunately I don't have a RPi3+ to test.
